# Generated by Django 2.1.4 on 2019-05-13 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('access_code', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='customer_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
